steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file
      - env.sh.enc
      - --plaintext-file
      - env.sh
      - --location
      - global
      - --keyring
      - dailyring
      - --key
      - dailykey
    id: decrypt env vars
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file
      - creds/creds.json.enc
      - --plaintext-file
      - creds/creds.json
      - --location
      - global
      - --keyring
      - dailyring
      - --key
      - dailykey
    id: decrypt creds
  - name: python:3.8-slim-buster
    args:
      - bash
      - app.sh
      
    waitFor:
      - decrypt creds
timeout: 900s
